version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/story-generator"
      - "/front-end"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directories:
      - "/story-generator"
      - "/front-end"
    schedule:
      interval: "weekly"
